(() => {
  const cfg=window.CLINIC_CONFIG||{}; const isLive=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.DEMO_MODE); const client=isLive?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
  const $=id=>document.getElementById(id); const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const seed={settings:{clinic_name:'Clinic Website Prototype',doctor_name:'Demo Doctor Profile',qualification:'MBBS, MD – General Medicine (Placeholder)',hero_intro:'Prototype clinic website.',doctor_bio:'Placeholder doctor biography.',experience:'Sample profile',consultation_mode:'In-clinic',next_availability:'Testing only',address:'Placeholder – Hyderabad',phone:'+91 90000 00000',email:'clinic@example.com',clinic_hours:'Sample hours'},services:[],facilities:[],articles:[]};
  const state={settings:null,services:[],facilities:[],articles:[],appointments:[],bookingConfig:null,schedule:[],blockedDates:[],editor:null};
  const demoGet=(k,f)=>{try{return JSON.parse(localStorage.getItem(`clinic_${k}`))??f}catch{return f}}; const demoSet=(k,v)=>localStorage.setItem(`clinic_${k}`,JSON.stringify(v));

  async function authInit(){if(!isLive){$('demoBanner').classList.remove('hidden');$('adminView').classList.remove('hidden');await loadAll();return;}const {data:{session}}=await client.auth.getSession();if(session){$('adminView').classList.remove('hidden');await loadAll();}else $('loginView').classList.remove('hidden');}
  async function login(e){e.preventDefault();const box=$('loginNotice');box.className='notice notice-info';box.textContent='Signing in…';const {error}=await client.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error){box.className='notice notice-error';box.textContent=error.message;return;}$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');await loadAll();}

  async function loadAll(){
    if(!isLive){state.settings=demoGet('settings',seed.settings);state.services=demoGet('services',seed.services);state.facilities=demoGet('facilities',seed.facilities);state.articles=demoGet('articles',seed.articles);state.appointments=demoGet('appointments',[]);state.bookingConfig=demoGet('bookingConfig',{id:1,slot_minutes:20,booking_window_days:30,min_notice_hours:2,timezone:'Asia/Kolkata'});state.schedule=demoGet('schedule',[{id:1,day_of_week:1,start_time:'09:00',end_time:'12:00',active:true},{id:2,day_of_week:1,start_time:'17:00',end_time:'20:00',active:true}]);state.blockedDates=demoGet('blockedDates',[]);
    } else {
      const [s,sv,f,a,ap,bc,ws,bd]=await Promise.all([client.from('site_settings').select('*').eq('id',1).single(),client.from('services').select('*').order('display_order'),client.from('facilities').select('*').order('display_order'),client.from('articles').select('*').order('published_at',{ascending:false}),client.from('appointments').select('*').order('created_at',{ascending:false}),client.from('appointment_config').select('*').eq('id',1).single(),client.from('weekly_schedule').select('*').order('day_of_week').order('start_time'),client.from('blocked_dates').select('*').order('blocked_date')]);
      const error=[s,sv,f,a,ap,bc,ws,bd].find(x=>x.error)?.error;if(error){alert(`Could not load admin data: ${error.message}\n\nIf this mentions appointment_config or weekly_schedule, run the Version 2 SQL migration first.`);return;}
      Object.assign(state,{settings:s.data,services:sv.data||[],facilities:f.data||[],articles:a.data||[],appointments:ap.data||[],bookingConfig:bc.data,schedule:ws.data||[],blockedDates:bd.data||[]});
    } renderAll();
  }
  function renderAll(){
    $('metricPending').textContent=state.appointments.filter(x=>x.status==='pending').length;$('metricServices').textContent=state.services.filter(x=>x.active).length;$('metricArticles').textContent=state.articles.filter(x=>x.published).length;$('metricFacilities').textContent=state.facilities.filter(x=>x.active).length;
    renderAppointments();renderList('serviceEditor','services');renderList('facilityEditor','facilities');renderArticles();fillSettings();fillBookingRules();renderSchedule();renderBlockedDates();
  }
  function renderAppointments(){const row=(x,actions=true)=>`<tr><td><strong>${safe(x.patient_name)}</strong></td><td>${safe(x.phone)}${x.email?`<br><small>${safe(x.email)}</small>`:''}</td><td>${safe(x.appointment_date)}</td><td>${safe(x.preferred_slot)}</td><td><span class="status status-${safe(x.status)}">${safe(x.status)}</span></td>${actions?`<td><select class="appt-status" data-id="${safe(x.id)}"><option ${x.status==='pending'?'selected':''}>pending</option><option ${x.status==='confirmed'?'selected':''}>confirmed</option><option ${x.status==='completed'?'selected':''}>completed</option><option ${x.status==='cancelled'?'selected':''}>cancelled</option></select></td>`:''}</tr>`;$('appointmentsTable').innerHTML=state.appointments.length?state.appointments.map(x=>row(x,true)).join(''):'<tr><td colspan="6" class="empty">No appointment requests yet.</td></tr>';$('recentAppointments').innerHTML=state.appointments.length?state.appointments.slice(0,5).map(x=>`<tr><td>${safe(x.patient_name)}</td><td>${safe(x.appointment_date)}</td><td>${safe(x.preferred_slot)}</td><td><span class="status status-${safe(x.status)}">${safe(x.status)}</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty">No appointment requests yet.</td></tr>';document.querySelectorAll('.appt-status').forEach(el=>el.onchange=()=>updateAppointment(el.dataset.id,el.value));}
  async function updateAppointment(id,status){if(!isLive){const x=state.appointments.find(a=>String(a.id)===String(id));if(x)x.status=status;demoSet('appointments',state.appointments);renderAll();return;}const {error}=await client.from('appointments').update({status}).eq('id',id);if(error)alert(error.message);else await loadAll();}

  function fillBookingRules(){const c=state.bookingConfig||{slot_minutes:20,booking_window_days:30,min_notice_hours:2,timezone:'Asia/Kolkata'};$('ruleSlotMinutes').value=String(c.slot_minutes||20);$('ruleWindowDays').value=c.booking_window_days||30;$('ruleMinNotice').value=c.min_notice_hours||0;$('ruleTimezone').value=c.timezone||'Asia/Kolkata';}
  async function saveBookingRules(e){e.preventDefault();const payload={id:1,slot_minutes:Number($('ruleSlotMinutes').value),booking_window_days:Number($('ruleWindowDays').value),min_notice_hours:Number($('ruleMinNotice').value),timezone:$('ruleTimezone').value.trim()||'Asia/Kolkata'};const box=$('bookingRulesNotice');try{if(!isLive){state.bookingConfig=payload;demoSet('bookingConfig',payload);}else{const {error}=await client.from('appointment_config').upsert(payload);if(error)throw error;}box.className='notice notice-success';box.textContent='Booking rules saved. New patient slot lists will use these rules.';await loadAll();}catch(err){box.className='notice notice-error';box.textContent=err.message;}}
  function timeVal(v){return String(v||'').slice(0,5)}
  function renderSchedule(){const rows=state.schedule||[];$('scheduleEditor').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Day</th><th>From</th><th>To</th><th>Active</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td><select class="sch-day" data-id="${x.id}">${DAYS.map((d,i)=>`<option value="${i}" ${Number(x.day_of_week)===i?'selected':''}>${d}</option>`).join('')}</select></td><td><input class="sch-start" data-id="${x.id}" type="time" value="${safe(timeVal(x.start_time))}"></td><td><input class="sch-end" data-id="${x.id}" type="time" value="${safe(timeVal(x.end_time))}"></td><td><input class="sch-active" data-id="${x.id}" type="checkbox" ${x.active?'checked':''}></td><td><div class="actions"><button class="btn btn-soft btn-sm sch-save" data-id="${x.id}">Save</button><button class="btn btn-danger btn-sm sch-delete" data-id="${x.id}">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No working hours configured. Add a working window.</div>';document.querySelectorAll('.sch-save').forEach(b=>b.onclick=()=>saveScheduleRow(b.dataset.id));document.querySelectorAll('.sch-delete').forEach(b=>b.onclick=()=>deleteScheduleRow(b.dataset.id));}
  async function addScheduleRow(){const payload={day_of_week:1,start_time:'09:00',end_time:'12:00',active:true};if(!isLive){state.schedule.push({...payload,id:Date.now()});demoSet('schedule',state.schedule);renderSchedule();return;}const {error}=await client.from('weekly_schedule').insert(payload);if(error)alert(error.message);else await loadAll();}
  async function saveScheduleRow(id){const payload={day_of_week:Number(document.querySelector(`.sch-day[data-id="${id}"]`).value),start_time:document.querySelector(`.sch-start[data-id="${id}"]`).value,end_time:document.querySelector(`.sch-end[data-id="${id}"]`).value,active:document.querySelector(`.sch-active[data-id="${id}"]`).checked};if(!payload.start_time||!payload.end_time||payload.start_time>=payload.end_time){alert('End time must be later than start time.');return;}if(!isLive){const x=state.schedule.find(r=>String(r.id)===String(id));Object.assign(x,payload);demoSet('schedule',state.schedule);renderSchedule();return;}const {error}=await client.from('weekly_schedule').update(payload).eq('id',id);if(error)alert(error.message);else await loadAll();}
  async function deleteScheduleRow(id){if(!confirm('Delete this working window?'))return;if(!isLive){state.schedule=state.schedule.filter(x=>String(x.id)!==String(id));demoSet('schedule',state.schedule);renderSchedule();return;}const {error}=await client.from('weekly_schedule').delete().eq('id',id);if(error)alert(error.message);else await loadAll();}
  function renderBlockedDates(){const rows=state.blockedDates||[];$('blockedDatesEditor').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Reason</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${safe(x.blocked_date)}</strong></td><td>${safe(x.reason||'—')}</td><td><button class="btn btn-danger btn-sm blocked-delete" data-date="${safe(x.blocked_date)}">Remove</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No blocked dates.</div>';document.querySelectorAll('.blocked-delete').forEach(b=>b.onclick=()=>deleteBlockedDate(b.dataset.date));}
  async function addBlockedDate(e){e.preventDefault();const payload={blocked_date:$('blockedDate').value,reason:$('blockedReason').value.trim()||null};if(!isLive){if(!state.blockedDates.some(x=>x.blocked_date===payload.blocked_date))state.blockedDates.push(payload);demoSet('blockedDates',state.blockedDates);e.target.reset();renderBlockedDates();return;}const {error}=await client.from('blocked_dates').upsert(payload);if(error)alert(error.message);else{e.target.reset();await loadAll();}}
  async function deleteBlockedDate(date){if(!isLive){state.blockedDates=state.blockedDates.filter(x=>x.blocked_date!==date);demoSet('blockedDates',state.blockedDates);renderBlockedDates();return;}const {error}=await client.from('blocked_dates').delete().eq('blocked_date',date);if(error)alert(error.message);else await loadAll();}

  function renderList(target,key){const rows=state[key];$(target).innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Order</th><th>Icon</th><th>Title</th><th>Description</th><th>Visible</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${safe(x.display_order)}</td><td style="font-size:1.3rem">${safe(x.icon)}</td><td><strong>${safe(x.title)}</strong></td><td>${safe(x.description)}</td><td>${x.active?'Yes':'No'}</td><td><div class="actions"><button class="btn btn-soft btn-sm edit-item" data-key="${key}" data-id="${safe(x.id)}">Edit</button><button class="btn btn-danger btn-sm delete-item" data-key="${key}" data-id="${safe(x.id)}">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No items yet.</div>';bindRowActions();}
  function renderArticles(){$('articleEditor').innerHTML=state.articles.length?`<div class="table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>Published</th><th>Date</th><th>Actions</th></tr></thead><tbody>${state.articles.map(x=>`<tr><td><strong>${safe(x.title)}</strong><br><small>${safe(x.excerpt)}</small></td><td>${safe(x.category)}</td><td>${x.published?'Yes':'No'}</td><td>${safe(x.published_at||'')}</td><td><div class="actions"><button class="btn btn-soft btn-sm edit-item" data-key="articles" data-id="${safe(x.id)}">Edit</button><button class="btn btn-danger btn-sm delete-item" data-key="articles" data-id="${safe(x.id)}">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No articles yet.</div>';bindRowActions();}
  function bindRowActions(){document.querySelectorAll('.edit-item').forEach(b=>b.onclick=()=>openEditor(b.dataset.key,b.dataset.id));document.querySelectorAll('.delete-item').forEach(b=>b.onclick=()=>deleteItem(b.dataset.key,b.dataset.id));}
  function openEditor(key,id=null){const existing=id?state[key].find(x=>String(x.id)===String(id)):null;state.editor={key,id};$('editorModal').classList.remove('hidden');if(key==='articles'){$('editorEyebrow').textContent='Health Library';$('editorTitle').textContent=existing?'Edit article':'New article';$('editorFields').innerHTML=`<div class="field full"><label>Title</label><input name="title" required value="${safe(existing?.title||'')}"></div><div class="field"><label>Category</label><input name="category" value="${safe(existing?.category||'General health')}"></div><div class="field"><label>Publish date</label><input name="published_at" type="date" value="${safe(existing?.published_at||new Date().toISOString().slice(0,10))}"></div><div class="field full"><label>Short excerpt</label><textarea name="excerpt" rows="3" required>${safe(existing?.excerpt||'')}</textarea></div><div class="field full"><label>Article body</label><textarea name="content" rows="8" required>${safe(existing?.content||'')}</textarea></div><div class="field full"><label><input type="checkbox" name="published" ${existing?.published!==false?'checked':''}> Published on website</label></div>`;}else{const singular=key==='services'?'Service':'Facility';$('editorEyebrow').textContent=singular;$('editorTitle').textContent=existing?`Edit ${singular.toLowerCase()}`:`New ${singular.toLowerCase()}`;$('editorFields').innerHTML=`<div class="field"><label>Icon / emoji</label><input name="icon" value="${safe(existing?.icon||'✚')}"></div><div class="field"><label>Display order</label><input name="display_order" type="number" min="1" value="${safe(existing?.display_order||state[key].length+1)}"></div><div class="field full"><label>Title</label><input name="title" required value="${safe(existing?.title||'')}"></div><div class="field full"><label>Description</label><textarea name="description" rows="4" required>${safe(existing?.description||'')}</textarea></div><div class="field full"><label><input type="checkbox" name="active" ${existing?.active!==false?'checked':''}> Visible on website</label></div>`;}}
  async function saveEditor(e){e.preventDefault();const fd=new FormData(e.target),{key,id}=state.editor;let payload;if(key==='articles')payload={title:fd.get('title').trim(),category:fd.get('category').trim(),published_at:fd.get('published_at'),excerpt:fd.get('excerpt').trim(),content:fd.get('content').trim(),published:fd.get('published')==='on'};else payload={icon:fd.get('icon').trim()||'✚',display_order:Number(fd.get('display_order')||1),title:fd.get('title').trim(),description:fd.get('description').trim(),active:fd.get('active')==='on'};try{if(!isLive){if(id){const i=state[key].findIndex(x=>String(x.id)===String(id));state[key][i]={...state[key][i],...payload}}else state[key].push({...payload,id:Date.now()});demoSet(key,state[key]);}else{const q=id?client.from(key).update(payload).eq('id',id):client.from(key).insert(payload);const {error}=await q;if(error)throw error;}closeEditor();await loadAll();}catch(err){$('editorNotice').className='notice notice-error';$('editorNotice').textContent=err.message;}}
  async function deleteItem(key,id){if(!confirm('Delete this item?'))return;if(!isLive){state[key]=state[key].filter(x=>String(x.id)!==String(id));demoSet(key,state[key]);renderAll();return;}const {error}=await client.from(key).delete().eq('id',id);if(error)alert(error.message);else await loadAll();}
  function fillSettings(){const s=state.settings||seed.settings;$('sClinicName').value=s.clinic_name||'';$('sDoctorName').value=s.doctor_name||'';$('sQualification').value=s.qualification||'';$('sHeroIntro').value=s.hero_intro||'';$('sDoctorBio').value=s.doctor_bio||'';$('sExperience').value=s.experience||'';$('sMode').value=s.consultation_mode||'';$('sAvailability').value=s.next_availability||'';$('sAddress').value=s.address||'';$('sPhone').value=s.phone||'';$('sEmail').value=s.email||'';$('sHours').value=s.clinic_hours||'';}
  async function saveSettings(e){e.preventDefault();const payload={id:1,clinic_name:$('sClinicName').value.trim(),doctor_name:$('sDoctorName').value.trim(),qualification:$('sQualification').value.trim(),hero_intro:$('sHeroIntro').value.trim(),doctor_bio:$('sDoctorBio').value.trim(),experience:$('sExperience').value.trim(),consultation_mode:$('sMode').value.trim(),next_availability:$('sAvailability').value.trim(),address:$('sAddress').value.trim(),phone:$('sPhone').value.trim(),email:$('sEmail').value.trim(),clinic_hours:$('sHours').value.trim()},box=$('settingsNotice');try{if(!isLive){state.settings=payload;demoSet('settings',payload)}else{const {error}=await client.from('site_settings').upsert(payload);if(error)throw error}box.className='notice notice-success';box.textContent='Website details saved.';await loadAll()}catch(err){box.className='notice notice-error';box.textContent=err.message}}
  function closeEditor(){$('editorModal').classList.add('hidden');$('editorNotice').className='hidden';$('editorForm').reset();state.editor=null;}
  function switchTab(tab){document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('[data-section]').forEach(s=>s.classList.toggle('hidden',s.dataset.section!==tab));const labels={dashboard:['Overview','Manage the clinic website from one place.'],appointments:['Appointments','Review and update appointment requests.'],availability:['Availability','Control bookable days, timings, duration and clinic closures.'],services:['Services','Add, edit, reorder or hide clinical services.'],facilities:['Facilities','Show patients what is available at the clinic.'],articles:['Health Library','Publish practical educational articles without touching code.'],settings:['Website details','Update the doctor profile, clinic contact details and homepage text.']};$('pageTitle').textContent=labels[tab][0];$('pageSubtitle').textContent=labels[tab][1];}

  document.querySelectorAll('.side-nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));
  $('addServiceBtn').onclick=()=>openEditor('services');$('addFacilityBtn').onclick=()=>openEditor('facilities');$('addArticleBtn').onclick=()=>openEditor('articles');$('addScheduleBtn').onclick=addScheduleRow;
  $('bookingRulesForm').addEventListener('submit',saveBookingRules);$('blockedDateForm').addEventListener('submit',addBlockedDate);$('editorClose').onclick=closeEditor;$('editorCancel').onclick=closeEditor;$('editorForm').addEventListener('submit',saveEditor);$('settingsForm').addEventListener('submit',saveSettings);$('loginForm').addEventListener('submit',login);$('logoutBtn').onclick=async()=>{if(isLive)await client.auth.signOut();location.reload();};authInit();
})();
