window.MED_NOTES_PRODUCTS = [
  {
    id: 'iv-fluids',
    title: 'IV Fluids: Physiology, Protocols & Clinical Use',
    shortTitle: 'IV Fluids',
    subject: 'General Medicine',
    category: 'Medicine',
    description: 'A compact revision resource covering fluid physiology, major fluid types, clinical scenarios, resuscitation principles and worked calculations.',
    format: 'PDF notes',
    language: 'English',
    pages: 11,
    edition: '2026 review copy',
    author: 'Dr. S. Kaushik Anurag, MBBS',
    price: 0,
    status: 'available',
    tone: 'blue',
    symbol: 'H₂O',
    file: 'IV_Fluids_Physiology_and_Protocols.pdf',
    highlights: [
      'Body-fluid compartments and core physiology',
      'Crystalloids and colloids at a glance',
      'Maintenance and resuscitation principles',
      'Clinical scenarios and worked calculations'
    ],
    audience: [
      'MBBS students revising core concepts',
      'NEET-PG learners seeking quick recall',
      'Readers who prefer concise clinical tables'
    ]
  },
  {
    id: 'respiratory-rapid-revision',
    title: 'Respiratory Medicine Rapid Revision',
    shortTitle: 'Respiratory Revision',
    subject: 'Respiratory Medicine',
    category: 'Respiratory',
    description: 'A planned high-yield respiratory medicine revision pack with structured concepts, differentials and quick-reference tables.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'cyan',
    symbol: 'O₂'
  },
  {
    id: 'abg-interpretation',
    title: 'ABG Interpretation: A Step-by-Step Guide',
    shortTitle: 'ABG Interpretation',
    subject: 'Clinical Diagnostics',
    category: 'Diagnostics',
    description: 'A planned visual approach to acid–base interpretation, compensation and commonly tested ABG patterns.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'indigo',
    symbol: 'pH'
  },
  {
    id: 'ecg-essentials',
    title: 'ECG Essentials for Rapid Revision',
    shortTitle: 'ECG Essentials',
    subject: 'Clinical Diagnostics',
    category: 'Diagnostics',
    description: 'A planned quick-reference resource for systematic ECG reading and essential high-yield patterns.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'navy',
    symbol: 'ECG'
  },
  {
    id: 'emergency-algorithms',
    title: 'Emergency Medicine: Core Algorithms',
    shortTitle: 'Emergency Algorithms',
    subject: 'Emergency Medicine',
    category: 'Emergency',
    description: 'A planned collection of concise learning algorithms for common emergency-medicine topics.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'sky',
    symbol: 'ER'
  },
  {
    id: 'pharmacology-tables',
    title: 'Clinical Pharmacology Memory Tables',
    shortTitle: 'Pharmacology Tables',
    subject: 'Pharmacology',
    category: 'Pharmacology',
    description: 'A planned table-based revision resource for drug classes, mechanisms and important clinical considerations.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'violet',
    symbol: 'Rx'
  },
  {
    id: 'chest-xray-basics',
    title: 'Chest X-Ray Interpretation Basics',
    shortTitle: 'Chest X-Ray Basics',
    subject: 'Respiratory Medicine',
    category: 'Respiratory',
    description: 'A planned structured introduction to reading chest radiographs for examination-oriented learning.',
    format: 'PDF notes',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'slate',
    symbol: 'CXR'
  },
  {
    id: 'medicine-case-revision',
    title: 'Medicine Case Revision Workbook',
    shortTitle: 'Medicine Case Revision',
    subject: 'General Medicine',
    category: 'Medicine',
    description: 'A planned case-based workbook for organising clinical reasoning and examination revision.',
    format: 'PDF workbook',
    language: 'English',
    pages: null,
    edition: 'Planned',
    author: 'Dr. S. Kaushik Anurag',
    price: null,
    status: 'coming-soon',
    tone: 'blue',
    symbol: 'Hx'
  }
];
