-- Doctor Clinic Website — Supabase database setup
-- Run this entire file in Supabase > SQL Editor.
-- Then create an admin user in Authentication > Users and run the final INSERT shown below.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  clinic_name text not null default 'Dr. Aarogya Clinic',
  doctor_name text not null default 'Dr. Ananya Rao',
  qualification text,
  hero_intro text,
  doctor_bio text,
  experience text,
  consultation_mode text,
  next_availability text,
  address text,
  phone text,
  email text,
  clinic_hours text,
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  icon text default '✚',
  title text not null,
  description text not null,
  active boolean not null default true,
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.facilities (
  id bigint generated by default as identity primary key,
  icon text default '✚',
  title text not null,
  description text not null,
  active boolean not null default true,
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  category text default 'General health',
  excerpt text not null,
  content text not null,
  published boolean not null default true,
  published_at date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  patient_name text not null,
  phone text not null,
  email text,
  appointment_date date not null,
  preferred_slot text not null,
  status text not null default 'pending' check (status in ('pending','confirmed','completed','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.site_settings enable row level security;
alter table public.services enable row level security;
alter table public.facilities enable row level security;
alter table public.articles enable row level security;
alter table public.appointments enable row level security;
alter table public.admin_users enable row level security;

-- Public website can read published content.
create policy "public read settings" on public.site_settings for select to anon, authenticated using (true);
create policy "public read active services" on public.services for select to anon, authenticated using (active = true or public.is_admin());
create policy "public read active facilities" on public.facilities for select to anon, authenticated using (active = true or public.is_admin());
create policy "public read published articles" on public.articles for select to anon, authenticated using (published = true or public.is_admin());

-- Anyone can request an appointment, but only admins can read/update/delete requests.
create policy "public create appointment" on public.appointments for insert to anon, authenticated with check (status = 'pending');
create policy "admin read appointments" on public.appointments for select to authenticated using (public.is_admin());
create policy "admin update appointments" on public.appointments for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin delete appointments" on public.appointments for delete to authenticated using (public.is_admin());

-- Admin content management policies.
create policy "admin update settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin manage services" on public.services for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin manage facilities" on public.facilities for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin manage articles" on public.articles for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin see own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());

-- Least-privilege Data API grants. RLS still controls actual row access.
grant select on public.site_settings, public.services, public.facilities, public.articles to anon;
grant insert on public.appointments to anon;
grant select, insert, update, delete on public.site_settings, public.services, public.facilities, public.articles, public.appointments to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.site_settings (id, clinic_name, doctor_name, qualification, hero_intro, doctor_bio, experience, consultation_mode, next_availability, address, phone, email, clinic_hours)
values (1, 'Dr. Aarogya Clinic', 'Dr. Ananya Rao', 'MBBS, MD • General Medicine',
'Consult Dr. Ananya Rao for thoughtful, evidence-informed care. Request an appointment online, explore clinic facilities and read practical health education articles.',
'Dr. Ananya Rao focuses on preventive care, common adult health concerns and long-term condition management. The clinic is designed around clear explanations, appropriate follow-up and respectful patient experience.',
'12+ years', 'In-clinic', 'Today', 'Road No. 12, Banjara Hills, Hyderabad', '+91 90000 00000', 'clinic@example.com', 'Mon–Sat: 9 AM–12 PM & 5 PM–8 PM')
on conflict (id) do nothing;

insert into public.services (icon,title,description,active,display_order) values
('🩺','General Consultation','Evaluation and treatment planning for common adult health concerns.',true,1),
('❤️','Preventive Health','Risk assessment, screening guidance and practical preventive-care planning.',true,2),
('📈','Chronic Care Follow-up','Structured follow-up for long-term conditions and treatment adherence.',true,3),
('🧪','Report Review','Clinical interpretation of previously ordered routine laboratory reports.',true,4),
('💉','Vaccination Guidance','Age-appropriate vaccination counselling and scheduling guidance.',true,5),
('🌿','Lifestyle Counselling','Simple, sustainable conversations around sleep, activity and nutrition habits.',true,6);

insert into public.facilities (icon,title,description,active,display_order) values
('🪑','Comfortable Waiting Area','A clean, organised waiting area designed for a smoother clinic visit.',true,1),
('🧴','Hygiene Protocols','Routine surface hygiene and hand-sanitisation facilities for patients.',true,2),
('🧾','Digital Appointment Log','Appointment requests are visible to clinic staff in one admin dashboard.',true,3);

insert into public.articles (title,category,excerpt,content,published,published_at) values
('Blood pressure: what the numbers actually mean','Preventive care','A simple guide to systolic and diastolic readings, home monitoring and when to seek medical advice.','<p>Blood pressure is written as two numbers. The upper number is the pressure when the heart contracts; the lower number is the pressure between beats.</p><p>A single reading does not always tell the whole story. Clinicians often look at repeated measurements and your wider health context.</p><p><strong>Important:</strong> sudden severe symptoms require urgent medical attention.</p>',true,current_date),
('How to prepare for a routine doctor visit','Clinic guide','Five practical steps that can make a short consultation more useful for both patient and doctor.','<p>Bring a concise list of current medicines, allergies and the key question you want answered. If you have recent test reports, keep them organised by date.</p><p>A focused summary helps the clinician spend more time understanding and discussing the plan.</p>',true,current_date);

-- FINAL STEP AFTER YOU CREATE THE DOCTOR/ADMIN LOGIN IN SUPABASE AUTHENTICATION:
-- Replace the UUID below with that user's UUID, then run this one line separately:
-- insert into public.admin_users (user_id) values ('PASTE-AUTH-USER-UUID-HERE');
